export const ACHIEVEMENTS = {
  FIRST_WIN: 'FIRST_WIN',
  FIRST_WIN_STORE: 'FIRST_WIN_STORE',
  FIRST_WIN_BATTLE: 'FIRST_WIN_BATTLE',     // В админке, при ENEMY_DEFEAT_1 === 1
  FIRST_WIN_PVP: 'FIRST_WIN_PVP',
  COMPLETE_TUTORIAL: 'COMPLETE_TUTORIAL',
  COMPLETE_COMPANY: 'COMPLETE_COMPANY',     // В админке, при ENEMY_DEFEAT_6 === 1
  COMPLETE_STORE: 'COMPLETE_STORE',
  COMPLETE_INVENTORY: 'COMPLETE_INVENTORY',
  CNT_PARRY_BATTLE: 'CNT_PARRY_BATTLE',     // В админке, при PARRY_BATTLE === 25
  CNT_PARRY_PVP: 'CNT_PARRY_PVP',           // В админке, при PARRY_PVP === 10
  CNT_ENEMY_DEFEAT_1: 'CNT_ENEMY_DEFEAT_1', // В админке, при ENEMY_DEFEAT_1 === 30
  CNT_ENEMY_DEFEAT_3: 'CNT_ENEMY_DEFEAT_3', // В админке, при ENEMY_DEFEAT_3 === 20
  CNT_ENEMY_DEFEAT_5: 'CNT_ENEMY_DEFEAT_5', // В админке, при ENEMY_DEFEAT_5 === 10
  CNT_COINS: 'CNT_COINS',                   // В админке, при COINS === 5000
} as const

export type AchievementId = typeof ACHIEVEMENTS[keyof typeof ACHIEVEMENTS]

export const STATS = {
  GAMES_PLAYED: 'GAMES_PLAYED',
  GAMES_PLAYED_BATTLE: 'GAMES_PLAYED_BATTLE',
  GAMES_PLAYED_PVP: 'GAMES_PLAYED_PVP',
  WINS: 'WINS',
  WINS_BATTLE: 'WINS_BATTLE',
  WINS_PVP: 'WINS_PVP',
  CARDS_MATCHED: 'CARDS_MATCHED',
  PARRY_BATTLE: 'PARRY_BATTLE',
  PARRY_PVP: 'PARRY_PVP',
  ENEMY_DEFEAT_1: 'ENEMY_DEFEAT_1',
  ENEMY_DEFEAT_2: 'ENEMY_DEFEAT_2',
  ENEMY_DEFEAT_3: 'ENEMY_DEFEAT_3',
  ENEMY_DEFEAT_4: 'ENEMY_DEFEAT_4',
  ENEMY_DEFEAT_5: 'ENEMY_DEFEAT_5',
  ENEMY_DEFEAT_6: 'ENEMY_DEFEAT_6',
  COINS: 'COINS',
} as const

export type StatName = typeof STATS[keyof typeof STATS]

export const STEAM_SAVE_FILE = 'orion7-save.json'
