export const LEVELS_STATE_CONFIG = [
    {
        id: 1,
        x: 20,
        y: 20,
        title: 'Название уровня 1',
        description: 'Описание уровня 1',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        isPassed: true,
        isCurrent: true,
    },
    {
        id: 2,
        x: 37,
        y: 18,
        title: 'Название уровня 2',
        description: 'Описание уровня 2',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 3,
        x: 55,
        y: 15,
        title: 'Название уровня 3',
        description: 'Описание уровня 3',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 4,
        x: 70,
        y: 30,
        title: 'Название уровня 4',
        description: 'Описание уровня 4',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 5,
        x: 80,
        y: 45,
        title: 'Название уровня 5',
        description: 'Описание уровня 5',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 6,
        x: 70,
        y: 65,
        title: 'Название уровня 6',
        description: 'Описание уровня 6',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 7,
        x: 53,
        y: 70,
        title: 'Название уровня 7',
        description: 'Описание уровня 7',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 8,
        x: 43,
        y: 55,
        title: 'Название уровня 8',
        description: 'Описание уровня 8',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 9,
        x: 25,
        y: 50,
        title: 'Название уровня 9',
        description: 'Описание уровня 9',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 10,
        x: 15,
        y: 63,
        title: 'Название уровня 10',
        description: 'Описание уровня 10',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 11,
        x: 10,
        y: 80,
        title: 'Название уровня 11',
        description: 'Описание уровня 11',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        isPassed: false,
        isCurrent: false,
    },
  ]
  