export const LEVELS_STORE_CONFIG = [
    {
        id: 1,
        title: 'xxx1',
        description: 'yyy1',
        type: 'store',
        gameTimer: 30,
        cardCount: 6,
        cardCol: 3,
    },
    {
        id: 2,
        title: 'xxx2',
        description: 'yyy2',
        type: 'store',
        gameTimer: 25,
        cardCount: 8,
        cardCol: 4,
    },
    {
        id: 3,
        title: 'xxx3',
        description: 'yyy3',
        type: 'store',
        gameTimer: 30,
        cardCount: 10,
        cardCol: 5,
    },
    {
        id: 4,
        title: 'xxx4',
        description: 'yyy4',
        type: 'store',
        gameTimer: 20,
        cardCount: 10,
        cardCol: 5,
    },
    {
        id: 5,
        title: '',
        description: '',
        type: 'store',
        gameTimer: 30,
        cardCount: 12,
        cardCol: 4,
    },
    {
        id: 6,
        title: '',
        description: '',
        type: 'store',
        gameTimer: 20,
        cardCount: 12,
        cardCol: 4,
    },
    {
        id: 7,
        title: '',
        description: '',
        type: 'store',
        gameTimer: 40,
        cardCount: 16,
        cardCol: 4,
    },
    {
        id: 8,
        title: '',
        description: '',
        type: 'store',
        gameTimer: 35,
        cardCount: 16,
        cardCol: 4,
    },
    {
        id: 9,
        title: '',
        description: '',
        type: 'store',
        gameTimer: 30,
        cardCount: 16,
        cardCol: 4,
    },
    {
        id: 10,
        title: '',
        description: '',
        type: 'store',
        gameTimer: 35,
        cardCount: 20,
        cardCol: 5,
    },
    {
        id: 11,
        title: '',
        description: '',
        type: 'store',
        gameTimer: 30,
        cardCount: 20,
        cardCol: 5,
    },
]
  