import { GameLevelStateSimpleType, EnemyState } from "../services/game/types";

// Время в миллисекундах анимации одного круга состояний врага
const enemyStateDurations = {
    [EnemyState.DEFAULT]: 0,
    [EnemyState.START]: 500,
    [EnemyState.RUN]: 600,
    [EnemyState.ATTACK]: 1100,
    [EnemyState.STUN]: 400,
    [EnemyState.HIT]: 300,
    [EnemyState.DEAD]: 600,
}

export const LEVELS_STATE_CONFIG: GameLevelStateSimpleType[] = [
    {
        id: 0,
        x: 0,
        y: 0,
        title: 'Название уровня 0',
        description: 'Описание уровня 0',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [20, 10, 5, 10, 5],
        initialAttacks: [5, 3, 2, 3, 2],
        initialColors: ['red','blue','green','black','yellow'],
        enemyId: 0,
        enemyName: 'ПС-91',
        enemyHp: 50,
        enemyStateDurations,
        isPassed: true,
        isCurrent: false,
    },
    {
        id: 1,
        x: 72,
        y: 22,
        title: 'Название уровня 1',
        description: 'Описание уровня 1',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [8, 10, 6, 5, 9], // с какой периодичностью идет таймер, время до удара противника.
        initialAttacks: [20, 40, 10, 10, 20], // сила каждого удара. Сначала 20, потом 40 и тд... По-идее сумма должна быть 100
        initialColors: ['red','blue','green','black','yellow'],
        enemyId: 1,
        enemyName: 'Горлодер',
        enemyHp: 10,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 2,
        x: 50,
        y: 28,
        title: 'Название уровня 2',
        description: 'Описание уровня 2',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        enemyId: 2,
        enemyName: 'Голем',
        enemyHp: 15,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 3,
        x: 49,
        y: 38,
        title: 'Название уровня 3',
        description: 'Описание уровня 3',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        enemyId: 3,
        enemyName: 'Goblin',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 4,
        x: 20,
        y: 51,
        title: 'Название уровня 4',
        description: 'Описание уровня 4',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        enemyId: 1,
        enemyName: 'Goblin',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 5,
        x: 52,
        y: 56,
        title: 'Название уровня 5',
        description: 'Описание уровня 5',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        enemyId: 1,
        enemyName: 'Goblin',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 6,
        x: 79,
        y: 62,
        title: 'Название уровня 6',
        description: 'Описание уровня 6',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        enemyId: 1,
        enemyName: 'Goblin',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 7,
        x: 55,
        y: 66,
        title: 'Название уровня 7',
        description: 'Описание уровня 7',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        enemyId: 1,
        enemyName: 'Goblin',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 8,
        x: 19,
        y: 71,
        title: 'Название уровня 8',
        description: 'Описание уровня 8',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        enemyId: 1,
        enemyName: 'Goblin',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 9,
        x: 82,
        y: 86,
        title: 'Название уровня 9',
        description: 'Описание уровня 9',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        enemyId: 1,
        enemyName: 'Goblin',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 10,
        x: 39,
        y: 88,
        title: 'Название уровня 10',
        description: 'Описание уровня 10',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        enemyId: 1,
        enemyName: 'Goblin',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 101,
        x: 28,
        y: 23,
        title: 'Таверна',
        description: 'Можно сыграть за монетки',
        type: 'tavern',
        cardCount: 0,
        cardCol: 0,
        initialSeconds: [],
        initialAttacks: [],
        initialColors: [],
        enemyId: 1,
        enemyName: 'Goblin',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 102,
        x: 83,
        y: 6,
        title: 'Советская база',
        description: 'Обучение',
        type: 'base',
        cardCount: 0,
        cardCol: 0,
        initialSeconds: [],
        initialAttacks: [],
        initialColors: [],
        enemyId: 1,
        enemyName: 'Goblin',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: true,
        isCurrent: true,
    },
  ]
  