import { GameLevelStateSimpleType, EnemyState } from "../services/game/types";

// Время в миллисекундах анимации одного круга состояний врага
const enemyStateDurations = {
    [EnemyState.DEFAULT]: 0,
    [EnemyState.START]: 500,
    [EnemyState.RUN]: 600,
    [EnemyState.ATTACK]: 1100,
    [EnemyState.STUN]: 400,
    [EnemyState.HIT]: 300,
    [EnemyState.DEAD]: 600,
}

export const LEVELS_STATE_CONFIG: GameLevelStateSimpleType[] = [
    {
        id: 0,
        x: 0,
        y: 0,
        title: 'Тренировочная арена',
        description: 'Арена для отработки базовых элементов сражения.',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [20, 10, 5, 10, 5],
        initialAttacks: [5, 3, 2, 3, 2],
        initialColors: ['red','blue','green','black','yellow'],
        enemyId: 0,
        enemyName: 'ПС-91',
        enemyHp: 50,
        enemyStateDurations,
        isPassed: true,
        isCurrent: false,
    },
    {
        id: 1,
        x: 72,
        y: 22,
        title: 'Каньон отражений',
        description: 'Щирокое лесистое ущелье. Где скалах когда-то жил безобидные оборигены. Сейчас тут обитают щитомордники - не самые опасные существа, но очень агресивные.',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [7, 8, 6, 5, 9], // с какой периодичностью идет таймер, время до удара противника.
        initialAttacks: [16, 18, 14, 12, 20], // сила каждого удара. Сначала 20, потом 40 и тд.
        initialColors: ['green', 'yellow', 'red', 'black', 'blue'], // очередность цветов
        enemyId: 1,
        enemyName: 'Щитомордник',
        enemyHp: 65,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 2,
        x: 50,
        y: 28,
        title: 'Белое плато',
        description: 'Большая туманная равнина. Здесь обитают литоры — медлительные каменные создания, сливающиеся с поверхностью, и циклопы, чьи тяжёлые шаги ощущаются раньше, чем становятся видимыми.',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [6,4,3,4,5],
        initialAttacks: [12,8,8,10,12],
        initialColors: ['yellow','blue','green','black','red'],
        enemyId: 2,
        enemyName: 'Литор',
        enemyHp: 80,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 3,
        x: 49,
        y: 38,
        title: 'Серый мост',
        description: 'Древний каменный мост. Служит главной переправой на Плато Молчания.',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [7,6,7,5,6,7],
        initialAttacks: [24,20,24,18,22],
        initialColors: ['red','yellow','red','green','blue','black'],
        enemyId: 3,
        enemyName: 'Каменовский',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 4,
        x: 20,
        y: 50,
        title: 'Логово меркиля',
        description: 'Глубокая пещера, в виде черепа. Здесь обитает Меркиль - загадочное существо, поглотившее сотни душ и имеющее сотни лиц.',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,5,5,5,5],
        initialAttacks: [20,20,20,20,20],
        initialColors: ['yellow','red','blue','green','black'],
        enemyId: 4,
        enemyName: 'Меркиль',
        enemyHp: 80,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 5,
        x: 54,
        y: 57,
        title: 'Лощина титуса',
        description: 'Лесное плато, чарующее своей красотой и опасностью. Здесь обитает Титус - огромный летающий монстр, с когтями способными разорвать даже камень.',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [4,6,6,4,5],
        initialAttacks: [20,24,24,20,22],
        initialColors: ['black','green','red','yellow','blue'],
        enemyId: 5,
        enemyName: 'Титус',
        enemyHp: 150,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 6,
        x: 72,
        y: 68,
        title: 'Дежурный корабль',
        description: 'Летающий корабль, который служит переправой в огненную долину. Но ходят слухи, что корабль давно покинут и стал пристанищем опасного существа.',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [4,5,4,5,4],
        initialAttacks: [26,30,26,30,26],
        initialColors: ['red','green','yellow','blue','black'],
        enemyId: 6,
        enemyName: 'Небесный сева',
        enemyHp: 180,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 7,
        x: 19,
        y: 71,
        title: 'Остров 47',
        description: 'Парящий остров, где когда-то добывали редкий метал номер 47, который незаменим для создания топлива для порталов.',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        enemyId: 1,
        enemyName: '-',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 8,
        x: 82,
        y: 82,
        title: 'Неизвестная локация',
        description: 'Нет информации',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        enemyId: 1,
        enemyName: '-',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 9,
        x: 39,
        y: 88,
        title: 'Неизвестная локация',
        description: 'Нет информации',
        type: 'battle',
        cardCount: 10,
        cardCol: 5,
        initialSeconds: [5,10,2,2,3],
        initialAttacks: [20,40,10,10,12],
        initialColors: ['red','blue','green','black','yellow'],
        enemyId: 1,
        enemyName: '-',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 101,
        x: 28,
        y: 23,
        title: 'Таверна',
        description: 'Прекрасное место что бы превести дух, набраться сил, купить снаряжение или подзаработать монет.',
        type: 'tavern',
        cardCount: 0,
        cardCol: 0,
        initialSeconds: [],
        initialAttacks: [],
        initialColors: [],
        enemyId: 1,
        enemyName: 'Goblin',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: false,
        isCurrent: false,
    },
    {
        id: 102,
        x: 83,
        y: 6,
        title: 'Советская база',
        description: 'Посетите базу что получить необходимые знания для выживания в этом мире.',
        type: 'base',
        cardCount: 0,
        cardCol: 0,
        initialSeconds: [],
        initialAttacks: [],
        initialColors: [],
        enemyId: 1,
        enemyName: 'Goblin',
        enemyHp: 100,
        enemyStateDurations,
        isPassed: true,
        isCurrent: true,
    },
  ]
  