export const LEVELS_STORE_CONFIG = [
    {
        id: 1,
        title: 'Грог Камнеклык',
        description: '',
        type: 'store',
        gameTimer: 20,
        cardCount: 6,
        cardCol: 3,
        coins: 5,
    },
    {
        id: 2,
        title: 'Тарн Глухой',
        description: '',
        type: 'store',
        gameTimer: 20,
        cardCount: 8,
        cardCol: 4,
        coins: 10,
    },
    {
        id: 3,
        title: 'Ирма Пепел',
        description: '',
        type: 'store',
        gameTimer: 25,
        cardCount: 10,
        cardCol: 5,
        coins: 20,
    },
    {
        id: 4,
        title: 'Брон Лис',
        description: '',
        type: 'store',
        gameTimer: 20,
        cardCount: 10,
        cardCol: 5,
        coins: 30,
    },
    {
        id: 5,
        title: 'Урзах Пустоглаз',
        description: '',
        type: 'store',
        gameTimer: 30,
        cardCount: 12,
        cardCol: 4,
        coins: 50,
    },
    {
        id: 6,
        title: 'Брак Шраморук',
        description: '',
        type: 'store',
        gameTimer: 25,
        cardCount: 12,
        cardCol: 4,
        coins: 75,
    },
    {
        id: 7,
        title: 'Харг Треснутый Панцирь',
        description: '',
        type: 'store',
        gameTimer: 40,
        cardCount: 16,
        cardCol: 4,
        coins: 100,
    },
    {
        id: 8,
        title: 'Мракс Обломок',
        description: '',
        type: 'store',
        gameTimer: 35,
        cardCount: 16,
        cardCol: 4,
        coins: 150,
    },
    {
        id: 9,
        title: 'Зурн Глухорык',
        description: '',
        type: 'store',
        gameTimer: 30,
        cardCount: 16,
        cardCol: 4,
        coins: 200,
    },
    {
        id: 10,
        title: 'Ворг Кристаллоспин',
        description: '',
        type: 'store',
        gameTimer: 50,
        cardCount: 20,
        cardCol: 5,
        coins: 300,
    },
    {
        id: 11,
        title: 'Гулт Разлом',
        description: '',
        type: 'store',
        gameTimer: 40,
        cardCount: 20,
        cardCol: 5,
        coins: 400,
    },
]
  