export * from './game-page'
export * from './game-page-battle'
export * from './leader-board-page'
export * from './main-page'
export * from './not-found-page'
export * from './choose-level-page'
export * from './error-page'